/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mars.glb --transform -k
*/

import { useGLTF } from "@react-three/drei";

export function MarsModel(props) {
  const { nodes, materials } = useGLTF("./mars-transformed.glb", false, true);
  return (
    <group {...props} dispose={null}>
      <mesh
        visible
        scale={[0.005, 0.005, 0.005]}
        position={[0, 0, 0]}
        name="Cube008"
        geometry={nodes.Cube008.geometry}
        material={materials["Default OBJ.005"]}
      />
    </group>
  );
}

useGLTF.preload("./mars-transformed.glb");
